[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.textpad]
    animation = "fromTop"
    command = "mousepad Documents/personal/scratchpad.txt"
    class = "mousepad-droppad"
    size = "50% 60%"
    max_size = "1920px 100%"
    margin = 10 

[scratchpads.term]
    animation = "fromTop"
    command = "kitty --class kitty-dropterm"
    class = "kitty-dropterm"
    size = "75% 60%"
    max_size = "1920px 100%"
    margin = 50

# [scratchpads.term]
#     animation = "fromTop"
#     command = "foot --app-id foot-dropterm"
#     class = "foot-dropterm"
#     size = "75% 60%"
