[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-mocha"
# dark = "kanagawa"
# light = "kanagawa"
# dark = "rose-pine"
# light = "rose-pine"
# dark = "everforest-medium"
# light = "everforest-medium"
